# Generated by Django 4.2.5 on 2024-01-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DmsApp', '0003_remove_organization_user_remove_volunteer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
    ]
