# Generated by Django 4.2.1 on 2024-06-12 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DmsApp', '0004_remove_organization_email_remove_volunteer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='DmsApp.volunteer'),
        ),
    ]
